### ISSUE TITLE
Not restarting vaani.client 

### ISSUE THREAD

**Issue by tilmankamp** [mozilla/vaani.setup#4] opened 2016-07-20 13:48 UTC
On Raspberry Pi the vaani.client service is not restarted after successful Evernote token registration. Workaround for the time being: rebooting.

**Comment by davidflanagan** [comment] 2016-07-20 21:18
Weird. It works for me on Raspberry Pi.
How do you have your .service files configured in /lib/systemd/system/  ?

You should have these files there:

vaani.service
vaani-client.service
git-auto-updater.service

The only service that should be enabled is vaani-client.service. That one will start on boot, and will start the other two once it verifies that wifi is up and an oauth token is available.

(Note that the version you were using when you filed this bug did not start git-auto-updater. That was added just an hour ago.)

Also note that vaani.setup does do a "systemctl restart vaani" so if the vaani service is already running, it should get restarted. But if it is not running, it should also get started.  

This is a "works for me" issue, so I can't really do anything without more data.

If you can reproduce it, then instead of rebooting, please log into the device and get the logs with:

$ sudo journalctl -b -u vaani-setup > /tmp/log

Attaching the log here might help me see what is going on.

**Comment by tilmankamp** [comment] 2016-07-21 12:32
> The only service that should be enabled is vaani-client.service. That one will start on boot, and will start the other two once it verifies that wifi is up and an oauth token is available.

This was the essential hint. Thanks. I just worked on an outdated version and had no git-auto-updater.service yet.

**Comment by davidflanagan** [comment] 2016-07-21 15:26
It sounds like I can close this, then

**Closed by davidflanagan** 2016-07-21 15:26 UTC
